-- QUERY 1
SELECT DEPARTMENT_ID,COUNT(*) AS EMPLOYEE_COUNT,AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

--QUERY 2
SELECT JOB_ID,COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY JOB_ID;

-- QUERY 3
SELECT FIRST_NAME,HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE > 
(SELECT HIRE_DATE 
FROM EMPLOYEES
WHERE EMPLOYEE_ID=110);

-- QUERY 4
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 
(SELECT DEPARTMENT_ID
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING MAX(SALARY) >= 15000);

-- QUERY 5
SELECT DISTINCT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID
FROM EMPLOYEES
WHERE SALARY < ANY
(SELECT SALARY 
FROM EMPLOYEES
WHERE JOB_ID='IT_PROG');

-- QUERY 6
SELECT * 
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN
(SELECT EMPLOYEE_ID
FROM JOB_HISTORY);

-- QUERY 7
SELECT MANAGER_ID,MIN(SALARY)
FROM (SELECT MANAGER_ID,SALARY
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL) E
GROUP BY E.MANAGER_ID 
HAVING MIN(SALARY) <> 2000
ORDER BY MIN(SALARY) DESC;

--QUERY 8
CREATE TABLE EMPLOYEE_BKP AS
SELECT * FROM hr.EMPLOYEES
WHERE 1=2;

INSERT INTO EMPLOYEE_BKP
SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID = 
(SELECT EMPLOYEE_ID
FROM JOB_HISTORY
WHERE START_DATE = '13-JAN-01');

-- QUERY 9
UPDATE EMPLOYEE_BKP
SET SALARY = SALARY + (SALARY * 0.2)
WHERE JOB_ID IN 
(SELECT JOB_ID
FROM JOBS
WHERE MIN_SALARY = 6000);


-- QUERY 10
DELETE FROM EMPLOYEE_BKP
WHERE EMPLOYEE_ID = 
(SELECT EMPLOYEE_ID
FROM EMPLOYEES 
WHERE JOB_ID 
LIKE 'FI%' AND
EMPLOYEE_ID IN
(SELECT MANAGER_ID 
FROM EMPLOYEES));

-- QUERY 11
SELECT DEPARTMENT_ID,COUNT(*)
FROM (SELECT *
FROM EMPLOYEES
WHERE SALARY>2000)
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 5
ORDER BY DEPARTMENT_ID;

CREATE TABLE STAFF(
staffNo VARCHAR(4) NOT NULL PRIMARY KEY,
fName VARCHAR(6) NOT NULL,
lName VARCHAR(6) NOT NULL,
position VARCHAR(10) NOT NULL,
sex VARCHAR(1) NOT NULL,
DOB DATE NOT NULL,
salary NUMBER NOT NULL,
branchNo VARCHAR(4) NOT NULL
);

SELECT MONTHS_BETWEEN(SYSDATE,HIRE_DATE)
FROM EMPLOYEES;