-- QUERY 1
SELECT E.FIRST_NAME,E.LAST_NAME,E.JOB_ID,D.DEPARTMENT_NAME,E.SALARY
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME;

-- QUERY 2
SELECT D.DEPARTMENT_NAME
FROM DEPARTMENTS D INNER JOIN EMPLOYEES E
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING COUNT(E.DEPARTMENT_ID) >= 2;

-- QUERY 3
SELECT *
FROM EMPLOYEES E LEFT JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
WHERE J.MIN_SALARY > E.SALARY;

-- QUERY 4
SELECT E.FIRST_NAME,E.LAST_NAME,J.JOB_TITLE,E.SALARY*12 AS ANNUAL_SALARY,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,L.CITY
FROM EMPLOYEES E JOIN JOBS J ON (E.JOB_ID=J.JOB_ID)
JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L ON (L.LOCATION_ID=D.LOCATION_ID)
WHERE E.SALARY*12 = 60000 AND J.JOB_TITLE <> 'Analyst';

-- QUERY 5
SELECT DISTINCT E.*
FROM EMPLOYEES E JOIN EMPLOYEES EM
ON (E.EMPLOYEE_ID = EM.MANAGER_ID);

-- QUERY 6
SELECT DISTINCT D.DEPARTMENT_ID,D.DEPARTMENT_NAME
FROM DEPARTMENTS D JOIN EMPLOYEES E
ON(D.DEPARTMENT_ID NOT IN E.DEPARTMENT_ID);

-- QUERY 7
SELECT E.FIRST_NAME,E.LAST_NAME,E.SALARY,D.DEPARTMENT_NAME
FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID);

-- QUERY 8
SELECT E.FIRST_NAME,E.LAST_NAME,J.JOB_ID,D.DEPARTMENT_NAME,L.STREET_ADDRESS,L.CITY
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN JOBS J ON (E.JOB_ID = J.JOB_ID)
JOIN LOCATIONS L ON(D.LOCATION_ID = L.LOCATION_ID)
WHERE L.STATE_PROVINCE IS NULL;

-- QUERY 9
SELECT J.*
FROM JOBS J
LEFT JOIN EMPLOYEES E ON(J.JOB_ID = E.JOB_ID)
WHERE E.JOB_ID IS NULL;

-- QUERY 10
SELECT E.*
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L ON (L.LOCATION_ID=D.LOCATION_ID)
WHERE L.COUNTRY_ID='US' AND L.STATE_PROVINCE = 'Washington';