-- QUERY 1
SELECT FIRST_NAME,LAST_NAME
FROM EMPLOYEES;

-- QUERY 2
SELECT HIRE_DATE AS JOINING_DATE
FROM EMPLOYEES;

-- QUERY 3
SELECT FIRST_NAME || LAST_NAME AS FULL_NAME
FROM EMPLOYEES;

-- QUERY 4
SELECT * 
FROM EMPLOYEES
WHERE SALARY 
BETWEEN 20000 AND 30000;

-- QUERY 5
SELECT EMPLOYEE_ID,FIRST_NAME
FROM EMPLOYEES
WHERE DEPARTMENT_ID
BETWEEN 59 AND 101;

-- QUERY 6
SELECT FIRST_NAME,CITY 
FROM EMPLOYEES,LOCATIONS
WHERE CITY IN ('Toronto','Hiroshima','Sydney');

-- QUERY 7
SELECT * 
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%ll%';

-- QUERY 8
SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

-- QUERY 9
SELECT * 
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- QUERY 10
SELECT INITCAP(FIRST_NAME),LOWER(JOB_ID)
FROM EMPLOYEES;

-- QUERY 11
SELECT FIRST_NAME || LAST_NAME || JOB_ID,LENGTH(FIRST_NAME || LAST_NAME),INSTR(FIRST_NAME || LAST_NAME,'a')
FROM EMPLOYEES
WHERE JOB_ID LIKE 'SA%';

-- QUERY 12
SELECT EMPLOYEE_ID,EXTRACT(DAY FROM HIRE_DATE),EXTRACT(MONTH FROM HIRE_DATE)
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE)=2003;

-- QUERY 13
SELECT EMPLOYEE_ID,EXTRACT(MONTH FROM HIRE_DATE),EXTRACT(YEAR FROM HIRE_DATE)
FROM EMPLOYEES;

-- QUERY 14
SELECT FIRST_NAME || LAST_NAME, TO_CHAR(HIRE_DATE,'DD, Month YYYY')
FROM EMPLOYEES;

-- QUERY 15
SELECT LPAD(SALARY,LENGTH(SALARY)+1,'$')
FROM EMPLOYEES
WHERE FIRST_NAME = 'Neena';

-- QUERY 16
SELECT NEXT_DAY(SYSDATE,'Monday')
FROM DUAL;

-- QUERY 17
SELECT *
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%';

-- QUERY 18
SELECT SUBSTR(FIRST_NAME,LENGTH(FIRST_NAME)-3,3)
FROM EMPLOYEES;

-- QUERY 19
SELECT EMPLOYEE_ID,HIRE_DATE,MONTHS_BETWEEN(SYSDATE,HIRE_DATE),NEXT_DAY(HIRE_DATE,'Friday'),LAST_DAY(HIRE_DATE)
FROM EMPLOYEES
WHERE MONTHS_BETWEEN(SYSDATE,HIRE_DATE) > 100;

-- QUERY 20
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,SALARY *1.15 AS INCREMENTED_SALARY, (SALARY*1.15) - SALARY AS INCREMENTED_AMOUNT
FROM EMPLOYEES;

-- QUERY 21
SELECT FIRST_NAME,HIRE_DATE,TO_CHAR(HIRE_DATE,'Day') AS DAY
FROM EMPLOYEES
ORDER BY TO_CHAR(HIRE_DATE-1,'D');

-- QUERY 22
SELECT DEPARTMENT_ID,MANAGER_ID,ROUND(COMMISSION_PCT,1)
FROM EMPLOYEES;

-- QUERY 23
SELECT *
FROM EMPLOYEES
WHERE COMMISSION_PCT > 0 AND DEPARTMENT_ID NOT IN(90,100);

-- QUERY 24
SELECT *
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2010;

-- QUERY 25
SELECT UNIQUE JOB_TITLE
FROM JOBS,EMPLOYEES
WHERE MIN_SALARY BETWEEN 8000 AND 15000
AND COMMISSION_PCT IS NULL;

-- QUERY 26
SELECT FIRST_NAME,LAST_NAME,JOB_ID
FROM EMPLOYEES
WHERE (EMPLOYEE_ID BETWEEN 100 AND 150) 
AND (DEPARTMENT_ID BETWEEN 90 AND 100);

-- QUERY 27
SELECT SALARY + (COMMISSION_PCT * SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;