--QUERY 1
SELECT * FROM JOBS;

--QUERY 2
SELECT MIN_SALARY,MAX_SALARY FROM JOBS
WHERE JOB_TITLE='President';

--QUERY 3
SELECT * FROM EMPLOYEES
WHERE SALARY=20000;

--QUERY 4
SELECT JOB_ID FROM EMPLOYEES
WHERE SALARY >= 15000;

--QUERY 5
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID FROM EMPLOYEES
WHERE LAST_NAME='King';

--QUERY 6
SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID=50;

--QUERY 7
SELECT PHONE_NUMBER FROM EMPLOYEES
WHERE DEPARTMENT_ID=80 AND MANAGER_ID=100;

--QUERY 8
SELECT * FROM EMPLOYEES 
WHERE FIRST_NAME='John' OR FIRST_NAME='Neena' OR FIRST_NAME='Lency';

--QUERY 9
SELECT CITY FROM LOCATIONS
WHERE COUNTRY_ID='IT';

--QUERY 10
SELECT CITY FROM LOCATIONS
WHERE COUNTRY_ID!='IN' OR COUNTRY_ID='CH';

--QUERY 11
SELECT JOB_TITLE FROM JOBS
WHERE MIN_SALARY>8000 AND MIN_SALARY<15000;

--QUERY 12
SELECT PHONE_NUMBER FROM EMPLOYEES
WHERE DEPARTMENT_ID=90 AND JOB_ID!='ID_PROG';

--QUERY 13
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE>'12-DEC-07';

--QUERY 14
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE>'12-DEC-07' AND DEPARTMENT_ID=100;

--QUERY 15
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE>'12-DEC-07' AND DEPARTMENT_ID!=100;
