-- QUERY 1 IS ACCOUNT CREATION

-- QUERY 2
CREATE TABLE JOBS AS
SELECT * FROM hr.JOBS
WHERE 1=2;
ALTER TABLE JOBS ADD PRIMARY KEY (JOB_ID);

CREATE TABLE JOB_HISTORY AS
SELECT * FROM hr.job_history
WHERE 1=2;

-- QUERY 3
ALTER TABLE JOBS
MODIFY JOB_ID NUMBER;

-- QUERY 4
ALTER TABLE JOB_HISTORY
MODIFY JOB_ID NUMBER;

ALTER TABLE JOB_HISTORY
ADD FOREIGN KEY(JOB_ID)
REFERENCES JOBS(JOB_ID);

-- QUERY 5
INSERT INTO JOBS VALUES(420,'PAIN',2000,60000);
INSERT INTO JOB_HISTORY VALUES(1,'1-FEB-2010','2-APR-2010',420,3);

-- QUERY 6
ALTER TABLE JOBS ADD (JOB_NATURE VARCHAR(20));

-- QUERY 7
CREATE TABLE EMPLOYEE AS
SELECT * FROM hr.employees
WHERE 1=2;

-- QUERY 8
ALTER TABLE EMPLOYEE ADD PRIMARY KEY (EMPLOYEE_ID);
ALTER TABLE JOB_HISTORY
ADD FOREIGN KEY(EMPLOYEE_ID)
REFERENCES EMPLOYEE(EMPLOYEE_ID);

-- QUERY 9
ALTER TABLE JOBS DROP COLUMN JOB_NATURE;

-- QUERY 10
ALTER TABLE EMPLOYEE ADD CONSTRAINT CON_1 CHECK(FIRST_NAME=UPPER(FIRST_NAME));

-- QUERY 11
ALTER TABLE EMPLOYEE ADD CONSTRAINT SAL_CONS UNIQUE(SALARY);

-- QUERY 12
ALTER TABLE EMPLOYEE ADD CHECK (PHONE_NUMBER IS NOT NULL);

-- QUERY 13
INSERT INTO EMPLOYEE VALUES(1,'HAHA','LOL','ABCD',123456,'1-FEB-2010',420,20000,0.1,NULL,3);

-- QUERY 14
UPDATE EMPLOYEE SET SALARY=2000 WHERE EMPLOYEE_ID=105 AND SALARY < 1000;

--QUERY 15
ALTER TABLE EMPLOYEE ADD PRIMARY KEY(EMPLOYEE_ID,JOB_ID);
-- REASON => TABLE CAN ONLY HAVE ONE PRIMARY KEY

-- QUERY 16
CREATE INDEX INDX_JOB_ID ON JOB_HISTORY(JOB_ID);

--QUERY 17
TRUNCATE TABLE EMPLOYEE;
